# Generated by Django 5.2.7 on 2025-10-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guidelinepillar_guidelineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description about yourself/brand'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='style_self_desc',
            field=models.TextField(blank=True, help_text='How you describe your writing style (optional)'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='topical_keywords',
            field=models.TextField(blank=True, help_text='Comma or newline separated topics you usually cover'),
        ),
    ]
