# Generated by Django 5.2.7 on 2025-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_onboarding_bio_onboarding_style_self_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='source',
            field=models.CharField(choices=[('FILE', 'File'), ('TEXT', 'Typed')], default='FILE', max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(choices=[('TXT', 'Text (.txt)'), ('PDF', 'PDF (.pdf)'), ('TEXT', 'Typed')], max_length=5),
        ),
    ]
