# Generated by Django 5.2.7 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_upload_source_alter_upload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleprofile',
            name='fun_facts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
